### ISSUE TITLE
续命卡在36%

### ISSUE THREAD

**Issue by sqc2020** [Avenshy/mahjong-helper-majsoul#9]
完全按照https://github.com/Avenshy/majsoul_mod_plus#%E7%BB%AD%E5%91%BD%E8%AF%B4%E6%98%8E操作的
![image](https://user-images.githubusercontent.com/74816093/211956616-6507237a-5fce-4c0a-a896-382756fc8ce7.png)

**Comment by Avenshy** [comment]
你的报错让我无法相信是完全按照操作的...

看一下header editor的配置，我猜你按照原作者的配置方法做了。

**Comment by sqc2020** [comment]
> 你的报错让我无法相信是完全按照操作的...
> 
> 看一下header editor的配置，我猜你按原作者的配置方法做了。

抱歉的确是我的问题，我没注意到我几个月前安装的原方法，原方法优先生效了
![1673499404180](https://user-images.githubusercontent.com/74816093/211980363-93f3507d-a122-4e79-9a14-f3573660c2ac.png)
![image](https://user-images.githubusercontent.com/74816093/211980530-34cd1bda-0d4e-4515-b5a3-53c4b2414c8d.png)
